In [343]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [344]:
import numpy as np

In [345]:
x = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
], dtype = 'float64')
x.shape
x

(4, 2)

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [346]:
x_trans = x.T
x_trans.shape
x_trans

(2, 4)

array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]])

In [347]:
weights = np.array([0.6, 0.4])
weights
weights.shape

array([0.6, 0.4])

(2,)

In [348]:
bias = np.float64(0)

In [349]:
hl_1_n_1 = np.zeros((2,), dtype = 'float')
hl_1_n_1
hl_1_n_1.shape

array([0., 0.])

(2,)

In [350]:
target_vector = [0, 0, 0, 1]
target_vector

[0, 0, 0, 1]

In [351]:
def sigmoid(pred_score):
    
    return np.exp(pred_score)/np.add(1., np.exp(pred_score))

In [352]:
def linear_compute(x1, x2, w1, w2):
    
    hl_score = np.sum(
        [
            np.multiply(w1, x1),
            np.multiply(w2, x2),
            bias
        ],
        dtype = np.float64
    )
    
    return  hl_score

In [353]:
def gradient_at_sigmoid(pred_score):
    
    return np.multiply(pred_score, (1 - pred_score))

In [354]:
def gradient_at_loss(y, y_hat):
    
    return -np.subtract(y, y_hat)

In [355]:
jacob_hl_1_activation = np.array([sigmoid])

In [356]:
jacob_hl_1 = np.array([])

In [357]:
x_train_len = x_trans.shape[1]

In [358]:
np.square(2)

4

In [359]:
def compute_loss(y, y_hat):

    return np.divide(np.square(np.subtract(y, y_hat)), 2)

In [360]:
x_train_len = x.shape[0]
loss = list()

for epoch in range(0, 10):
    
    loss.append([])

    for i in range(0, x_train_len):
        
        w_i, w_ii = weights

        y = target_vector[i]

        x_i, x_ii = x[i]

        y_score = linear_compute(x_i, x_ii, w_i, w_ii)
        y_hat = sigmoid(y_score)


        loss1 = compute_loss(y, y_hat)

        del_l__by__del_y_hat = gradient_at_loss(y, y_hat)

        del_y_hat__by__del_z = gradient_at_sigmoid(y_hat)

        del_z__by__del_w_i = x_i

        del_z__by__del_w_ii = x_ii

        del_z__by__del_b = 1

        del_l__by__del_z = np.multiply(del_l__by__del_y_hat, del_y_hat__by__del_z)

        del_l__by__del_w_i = np.multiply(del_l__by__del_z, del_z__by__del_w_i)
        
        del_l__by__del_w_ii = np.multiply(del_l__by__del_z, del_z__by__del_w_ii)


        del_l__by__del_b = np.multiply(del_l__by__del_z, del_z__by__del_b)


        weights = weights - np.array([del_l__by__del_w_i, del_l__by__del_w_ii])
        
        loss[epoch].append(loss1)
        bias = np.subtract(bias, del_l__by__del_b)

        
for i in loss:
    print(i)

[0.125, 0.16149380181035808, 0.17001136561429891, 0.08924019362164669]
[0.09022746230839472, 0.1196533965216563, 0.12905571386794396, 0.12255685746371636]
[0.06843797747648774, 0.09547639913836868, 0.104927871979336, 0.1427858944798291]
[0.05454689367093193, 0.0815625892568062, 0.09056975691355287, 0.1531387122330396]
[0.04518102096343993, 0.07328727140382396, 0.08168815175901907, 0.15705074846054656]
[0.038477221196831425, 0.06819289483950472, 0.0759696656002549, 0.15689600183523383]
[0.03341573275497188, 0.06495667369036127, 0.07213987826127585, 0.15423225431437798]
[0.029419223150562408, 0.06282787646195849, 0.06946033192742967, 0.1500904805960953]
[0.02614779617749563, 0.061358254635602384, 0.06748342328374926, 0.1451579016088421]
[0.023394197570923796, 0.06027114201603998, 0.06593013693739862, 0.13988820888903108]
