In [1]:
import numpy as np
import pandas as pd

In [2]:
weights = np.array([0.1, 0.6])

data = np.array([[0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 1]])

In [3]:
print(weights.shape)
weights

(2,)


array([0.1, 0.6])

In [4]:
X = data[:, :2]
print(X.shape)
X

(4, 2)


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [5]:
X = X.T
print(X.shape)
X

(2, 4)


array([[0, 0, 1, 1],
       [0, 1, 0, 1]])

In [6]:
Y =  data[:, -1]
Y

array([0, 1, 1, 1])

In [7]:
Z = np.dot(weights, X)
Z

array([0. , 0.6, 0.1, 0.7])

In [47]:
def compute_sigmoid(z):
    
    sig = np.divide(1, np.add(1, np.exp(-z)))
    
    return sig

In [37]:
def compute_cost(y, y_hat, m, const = 2):
    
    total_cost = np.sum(np.divide(np.subtract(y, y_hat) ** 2, const))
    
    avg_cost = np.divide(total_cost, m)

    return avg_cost

In [44]:
def compute_gradient_of_cost(y, y_hat, m):
    
    grad = -np.subtract(y, y_hat)
    
    avg_grad = np.divide(grad, m)
    
    return avg_grad

In [48]:
y_hat = compute_sigmoid(Z)
y_hat

array([0.5       , 0.64565631, 0.52497919, 0.66818777])

In [38]:
avg_cost = compute_cost(Y, y_hat, len(y_hat))
avg_cost

0.08891294752305501

In [45]:
grad_cost = compute_gradient_of_cost(Y, y_hat, len(y_hat))
grad_cost

array([ 0.125     , -0.08858592, -0.1187552 , -0.08295306])

In [54]:
def del_y_hat__by__del_z(y_hat):
    """
        del_y_hat__by__del_z: $(y_hat)/$(z)
            As we know
            y_hat = sigmoid(z), therefore,
            $(sigmoid(z)) / $(z) : sigmoid(z)[1 - sigmoid(z)] OR [y_hat * (1 - y_hat)] 
    """
    
    one_sub_sigma = np.subtract(1, y_hat)
    
    grad = np.multiply(y_hat, one_sub_sigma)

    return grad

del_y_hat__by__del_z(y_hat)

[0.5        0.64565631 0.52497919 0.66818777]
[0.5        0.35434369 0.47502081 0.33181223]
[0.25       0.22878424 0.24937604 0.22171287]


True

In [ ]:
def ():
    
    