In [160]:
import numpy as np
import pandas as pd

In [161]:
weights = np.array([0.1, 0.6])

data = np.array([[0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 1]])

In [162]:
print(weights.shape)
weights

(2,)


array([0.1, 0.6])

In [163]:
X_O = data[:, :2]
print(X_O.shape)
X_O

(4, 2)


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [164]:
X = X_O.T
print(X.shape)
X

(2, 4)


array([[0, 0, 1, 1],
       [0, 1, 0, 1]])

In [165]:
Y =  data[:, -1]
Y

array([0, 1, 1, 1])

In [166]:
Z = np.dot(weights, X)
print(Z.shape)
Z

(4,)


array([0. , 0.6, 0.1, 0.7])

In [167]:
def compute_sigmoid(z):
    
    sig = np.divide(1, np.add(1, np.exp(-z)))
    
    return sig

In [168]:
def compute_cost(y, y_hat, m, const = 2):
    
    total_cost = np.sum(np.divide(np.subtract(y, y_hat) ** 2, const))
    
    avg_cost = np.divide(total_cost, m)

    return avg_cost

In [169]:
def compute_gradient_of_cost(y, y_hat, m):
    
    grad = -np.subtract(y, y_hat)
    
    avg_grad = np.divide(grad, m)
    
    return avg_grad

In [170]:
y_hat = compute_sigmoid(Z)
y_hat

array([0.5       , 0.64565631, 0.52497919, 0.66818777])

In [171]:
avg_cost = compute_cost(Y, y_hat, len(y_hat))
avg_cost

0.08891294752305501

In [172]:
grad_cost = compute_gradient_of_cost(Y, y_hat, len(y_hat))
grad_cost

array([ 0.125     , -0.08858592, -0.1187552 , -0.08295306])

In [173]:
def del_y_hat__by__del_z(y_hat):
    """
        del_y_hat__by__del_z: $(y_hat)/$(z)
            As we know
            y_hat = sigmoid(z), therefore,
            $(sigmoid(z)) / $(z) : sigmoid(z)[1 - sigmoid(z)] OR [y_hat * (1 - y_hat)] 
    """
    
    one_sub_sigma = np.subtract(1, y_hat)
    
    grad = np.multiply(y_hat, one_sub_sigma)

    return grad

grad_y_hat__by__del_z = del_y_hat__by__del_z(y_hat)

In [174]:
def final_grad_at__z(grad_cost, grad_y_hat__by__del_z):
    
    grad_at_node__z = np.multiply(grad_cost, grad_y_hat__by__del_z)
    
    return grad_at_node__z

In [175]:
grad_cost__by__del_z = final_grad_at__z(grad_cost, grad_y_hat__by__del_z)
grad_cost__by__del_z

array([ 0.03125   , -0.02026706, -0.0296147 , -0.01839176])

In [176]:
def del_z__by__del_weight0(X):
    """
    del_z__by__del_weight0 OR del_z__by__del_w0
    
    As we know that at Z node linear equation would be
    [
        weight[0] * X[0][0] + weight[1] * X[1][0]
        weight[0] * X[0][1] + weight[1] * X[1][1]
        weight[0] * X[0][2] + weight[1] * X[1][2]
        weight[0] * X[0][3] + weight[1] * X[1][3]
    ]
    
    Therefore it's differentiation w.r.t weight[0] would be 
        [X[0][0]        X[0][1]        X[0][2]        X[0][3]]

    """

    return X[0, :]

In [177]:
grad_z__by__del_weight0 = del_z__by__del_weight0(X)
grad_z__by__del_weight0

array([0, 0, 1, 1])

In [178]:
def del_z__by__del_weight1(X):
    """
    del_z__by__del_weight0 OR del_z__by__del_w1
    
    As we know that at Z node linear equation would be
    [
        weight[0] * X[0][0] + weight[1] * X[1][0]
        weight[0] * X[0][1] + weight[1] * X[1][1]
        weight[0] * X[0][2] + weight[1] * X[1][2]
        weight[0] * X[0][3] + weight[1] * X[1][3]
    ]
    
    Therefore it's differentiation w.r.t weight[1] would be 
        [X[1][0]        X[1][1]        X[1][2]        X[1][3]]

    """

    return X[1, :]

In [179]:
grad_z__by__del_weight1 = del_z__by__del_weight1(X)
grad_z__by__del_weight1

array([0, 1, 0, 1])

In [180]:
grad_cost__by__del_weight = np.dot( grad_cost__by__del_z, X_O)
grad_cost__by__del_weight

array([-0.04800646, -0.03865882])

In [181]:
"""
    Other way to compute :

    grad_cost__by__del_weight0
    and
    grad_cost__by__del_weight1
"""

"""
grad_cost__by__del_weight0 = np.sum(np.multiply(grad_cost__by__del_z, grad_z__by__del_weight0))
print(grad_cost__by__del_weight0)

grad_cost__by__del_weight1 = np.sum(np.multiply(grad_cost__by__del_z, grad_z__by__del_weight1))
print(grad_cost__by__del_weight1)
"""

'\ngrad_cost__by__del_weight0 = np.sum(np.multiply(grad_cost__by__del_z, grad_z__by__del_weight0))\nprint(grad_cost__by__del_weight0)\n\ngrad_cost__by__del_weight1 = np.sum(np.multiply(grad_cost__by__del_z, grad_z__by__del_weight1))\nprint(grad_cost__by__del_weight1)\n'