In [47]:
import numpy as np

In [48]:
data = np.array([[0, 0, 0], [0, 1, 0], [1, 0, 0], [1, 1, 1]], dtype = 'float32')

In [49]:
x = data[:, :2]
x

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [50]:
y = data[:, 2]
y

array([0., 0., 0., 1.], dtype=float32)

In [51]:
weights = np.array([0.1, 0.6])
weights

array([0.1, 0.6])

In [52]:
b = 0

In [53]:
d_train = x.T
d_train

array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]], dtype=float32)

In [54]:
def sigmoid(z):
    
    denom = np.add(1, np.exp(-z))
    
    sig = np.divide(1, denom)
    
    return sig

In [55]:
z_temp = np.dot(weights, d_train)
z_temp

array([0. , 0.6, 0.1, 0.7])

In [56]:
z = np.add(z_temp, b)
z

array([0. , 0.6, 0.1, 0.7])

In [57]:
y_hat = sigmoid(z)
y_hat

array([0.5       , 0.64565631, 0.52497919, 0.66818777])

In [58]:
def compute_bce(y, y_hat):
    """
    -1/m(y * log(y_hat) + (1 - y) * log(1 - y_hat))
    """
    true_event_prob = np.multiply(np.log(y_hat), y)

    one__sub__y = np.subtract(1, y)
    one__sub__y_hat = np.subtract(1, y_hat)
    false_event_prob_iii = np.multiply(one__sub__y, np.log(one__sub__y_hat))

    cost_elem = np.concatenate((true_event_prob, false_event_prob_iii))

    cost = np.sum(cost_elem)

    avg_cost = -np.divide(cost, len(y))

    return avg_cost

In [59]:
compute_bce(y, y_hat)

0.7195544600012148

In [60]:
np.divide(np.array([2, 4]), 2)

array([1., 2.])

In [61]:
def compute_final_del_cost__by__del_z_vector(y, y_hat, z):
        
    del_cost__by__del_y_hat = compute_local_del_cost__by__del_y_hat_vector(y, y_hat)
    del_y_hat__by__del_z = compute_local_del_y_hat__by__del_z_vector(z)
    
    del_cost__by__del_z = np.multiply(del_cost__by__del_y_hat, del_y_hat__by__del_z)
    
    return del_cost__by__del_z


def compute_local_del_cost__by__del_y_hat_vector(y, y_hat):
        
    grad_array = np.array([])
    for _y, _y_hat in zip(y, y_hat):
        
        local_gradient = -np.divide(_y, _y_hat) + np.divide((1 - _y), (1 - _y_hat))
        grad_array = np.append(grad_array, local_gradient)

    grad_array = np.divide(grad_array, len(y))

    return grad_array

In [62]:
local_del_cost__by__del_y_hat_vector = compute_local_del_cost__by__del_y_hat_vector(y, y_hat)
local_del_cost__by__del_y_hat_vector

array([ 0.5       ,  0.7055297 ,  0.52629273, -0.37414633])

In [63]:
def compute_local_del_y_hat__by__del_z_vector(z):

    grad_wrt_z = [sigmoid(output) * (1 - sigmoid(output)) for output in z]

    return grad_wrt_z

local_del_y_hat__by__del_z_vector = compute_local_del_y_hat__by__del_z_vector(z)
local_del_y_hat__by__del_z_vector

[0.25, 0.22878424045665732, 0.24937604019289197, 0.22171287329310904]

In [64]:
def compute_local_del_z__by__del_w_mtx(x):
    
    return x

local_del_z__by__del_w_mtx = compute_local_del_z__by__del_w_mtx(x)
local_del_z__by__del_w_mtx

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [65]:
compute_final_del_cost__by__del_z_vector(y, y_hat, z)

array([ 0.125     ,  0.16141408,  0.1312448 , -0.08295306])