In [20]:
import numpy as np

In [21]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype = 'float32')
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [22]:
weights = np.array([0.1, 0.6])
weights

array([0.1, 0.6])

In [23]:
b = 0

In [24]:
d_train = X.T
d_train

array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]], dtype=float32)

In [26]:
def sigmoid(z):
    
    denom = np.add(1, np.exp(-z))
    
    sig = np.divide(1, denom)
    
    return sig

In [25]:
z_temp = np.dot(weights, d_train)
z_temp

array([0. , 0.6, 0.1, 0.7])

In [28]:
z = np.add(z_temp, b)
z

array([0. , 0.6, 0.1, 0.7])

In [29]:
y_hat = sigmoid(z)
y_hat

array([0.5       , 0.64565631, 0.52497919, 0.66818777])