In [34]:
import numpy as np

In [35]:
data = np.array([[0, 0, 0], [0, 1, 0], [1, 0, 0], [1, 1, 1]], dtype = 'float32')

In [36]:
x = data[:, :2]
x

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [37]:
y = data[:, 2]
y

array([0., 0., 0., 1.], dtype=float32)

In [38]:
weights = np.array([0.1, 0.6])
weights

array([0.1, 0.6])

In [39]:
b = 0

In [40]:
d_train = x.T
d_train

array([[0., 0., 1., 1.],
       [0., 1., 0., 1.]], dtype=float32)

In [41]:
def sigmoid(z):
    
    denom = np.add(1, np.exp(-z))
    
    sig = np.divide(1, denom)
    
    return sig

In [42]:
z_temp = np.dot(weights, d_train)
z_temp

array([0. , 0.6, 0.1, 0.7])

In [43]:
z = np.add(z_temp, b)
z

array([0. , 0.6, 0.1, 0.7])

In [44]:
y_hat = sigmoid(z)
y_hat

array([0.5       , 0.64565631, 0.52497919, 0.66818777])

In [45]:
def compute_bce(y, y_hat):
    """
    -1/m(y * log(y_hat) + (1 - y) * log(1 - y_hat))
    """
    true_event_prob = np.multiply(np.log(y_hat), y)
    
    one__sub__y = np.subtract(1, y)
    one__sub__y_hat = np.subtract(1, y_hat)
    false_event_prob_iii = np.multiply(one__sub__y, np.log(one__sub__y_hat))
    
    cost_elem = np.concatenate((true_event_prob, false_event_prob_iii))
    
    cost = np.sum(cost_elem)
    
    avg_cost = -np.divide(cost, len(y))
    
    return avg_cost

In [46]:
compute_bce(y, y_hat)

0.7195544600012148

In [53]:
def comput_del_cost__by__del_y_hat_vector(y, y_hat):
        
    grad_array = np.array([])
    for _y, _y_hat in zip(y, y_hat):
        
        local_gradient = np.divide(y, y_hat) + np.divide((1 - y), (1 - y_hat))
        np.append(grad_array, local_gradient)


        return grad_array

In [54]:
local_del_cost__by__del_y_hat = comput_del_cost__by__del_y_hat_vector(y, y_hat)
local_del_cost__by__del_y_hat

TypeError: array() missing required argument 'object' (pos 1)